DROP TABLE ROLE;
DROP SEQUENCE ROLE_SEQ;


CREATE TABLE ROLE(ROLE_ID int NOT NULL PRIMARY KEY,ROLE_NAME varchar(50),DESCRIPTION varchar(200));

CREATE SEQUENCE ROLE_SEQ Start with 1 increment by 1;

DELETE FROM ROLE;

INSERT INTO ROLE (ROLE_ID,ROLE_NAME,DESCRIPTION) VALUES
(1,'HR','Human Resource');

INSERT INTO ROLE (ROLE_ID,ROLE_NAME,DESCRIPTION) VALUES
(2,'DEVELOPER','Application Developer');

INSERT INTO ROLE (ROLE_ID,ROLE_NAME,DESCRIPTION) VALUES
(3,'QA','Quality Assurance team');