DROP TABLE EMPLOYEE;
DROP SEQUENCE EMPLOYEE_SEQ;


CREATE TABLE EMPLOYEE(EMP_ID int NOT NULL PRIMARY KEY,FIRST_NAME varchar(50),LAST_NAME varchar(50),DOJ DATE);

CREATE SEQUENCE EMPLOYEE_SEQ Start with 1 increment by 1;


DELETE FROM EMPLOYEE;

INSERT INTO EMPLOYEE (EMP_ID,FIRST_NAME,LAST_NAME,DOJ) VALUES
(1,'Santhosh','G',current_date());

INSERT INTO EMPLOYEE (EMP_ID,FIRST_NAME,LAST_NAME,DOJ) VALUES
(2,'JOHN','G',current_date());