DROP TABLE EMPLOYEE_ROLE;
DROP SEQUENCE EMPLOYEE_ROLE_SEQ;


CREATE TABLE EMPLOYEE_ROLE(ID int NOT NULL PRIMARY KEY,EMP_ID int,FIRST_NAME varchar(50),LAST_NAME varchar(50),ROLE_ID int,ROLE_NAME varchar(50),DESCRIPTION varchar(200));

CREATE SEQUENCE EMPLOYEE_ROLE_SEQ Start with 1 increment by 1;

DELETE FROM EMPLOYEE_ROLE;

